---
title: "README"
author: "Christian"
date: "2024-04-27"
output: html_document
---


# French Trotting Data Analysis

This project analyzes horse racing data from French trotting races. One of the goals should be to explore factors influencing the race outcomes.


## Project Structure

* data_acquisition/: Scripts (written in Python) for acquiring horse racing data through API calls and storing them in a PostgreSQL database.
* data/: This folder contains raw data files and data files prepared for analysis.
* r_scripts/: This folder contains R scripts for extracting data from the database and for data cleaning and preparation for further analysis.
    + data_extraction_postgresql.R: This script extracts data from a database and saves it to a csv file.
    + french_trotting_2023_data_prep.R: This script cleans the raw data from 2023 and transforms it to better prepare it for analysis.
* notebooks/: Interactive notebooks for analysing data.
* sql_scripts/: Basic SQL queries used within the data extraction scripts.
* README.md: This file (you are here!).


## Data Acquisition

The req_reunions.py script performs the following tasks:

* Loads libraries.
* Makes API calls for every day within a user-defined time interval to get the french race calendar information (name of the racecourse, PMU number of the race) for that day, discipline).
* This information is then exported to a csv file whose name consists of the user-defined time interval (e.g. racesequidia_202303.csv for the data from March 2023).

The imports_race_jsons_to_db.py script performs the following tasks:

* Loads libraries.
* Reads the information from the csv file generated by the req_reunions.py script.
* Performs several API calls to get all infos regarding the races listed in the imported csv file.
* Establishes a connection to a database.
* Writes the information generated by the API calls (mainly on json per race and additional info like date and racecourse) to a table in the database.


## Data Description

The french_trotting_2023_raw_data.csv file contains data for french trotting races in 2023, including details like:

* Race date
* Name of the racecourse
* Informations about the race (surface, distance, prize money etc.)
* Informations about the horses in each race (name, finishing position etc.)


## Data Extraction

The data_extraction_postgresql.R script performs the following tasks:

* Loads libraries.
* Connects to a database.
* Loads a SQL query which is stored in a separate sql file.
* Uses the aforementioned query to extract relevant data from a table containing raw data in the database in which information about each race run in France is stored in a JSONB column. 
* Saves the extracted data to the french_trotting_2023_raw_data.csv file.


## Data Cleaning and Preparation

The french_trotting_2023_data_prep.R script performs the following tasks:

*



## Future Plans

* Conduct further data analysis to explore additional factors affecting race outcomes.
* Develop models to predict race outcomes based on historical data and analysis.





